import Link from 'next/link'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Terms of Service — ArgueBoss',
  description: 'Terms and conditions for using ArgueBoss.',
}

export default function TermsPage() {
  return (
    <div style={{ position: 'relative', minHeight: '100vh' }}>
      <div style={{
        position: 'fixed', width: 400, height: 400,
        background: 'rgba(232,37,26,0.07)', borderRadius: '50%',
        filter: 'blur(80px)', top: -100, right: -100,
        pointerEvents: 'none', zIndex: 1,
      }} />
      <div style={{
        position: 'fixed', width: 300, height: 300,
        background: 'rgba(232,37,26,0.04)', borderRadius: '50%',
        filter: 'blur(80px)', bottom: 100, left: -80,
        pointerEvents: 'none', zIndex: 1,
      }} />

      <div style={{ position: 'relative', zIndex: 5 }}>
        <Navbar />

        <div className="about-content" style={{
          maxWidth: 680, margin: '40px auto 80px',
          padding: '0 24px',
          animation: 'fadeInUp 0.6s ease both',
        }}>
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            background: 'var(--red-dim)',
            border: '1px solid rgba(232,37,26,0.3)',
            color: 'var(--red-light)',
            fontSize: 12, fontWeight: 600,
            letterSpacing: '1.5px', textTransform: 'uppercase',
            padding: '6px 16px', borderRadius: 100, marginBottom: 20,
          }}>Terms of Service</div>

          <h1 style={{
            fontFamily: "'Bebas Neue', sans-serif",
            fontSize: 'clamp(36px, 6vw, 60px)',
            lineHeight: 0.92, letterSpacing: 3,
            marginBottom: 20,
          }}>
            THE RULES.<br />
            <span style={{ color: 'var(--red)' }}>THEY'RE FAIR.</span>
          </h1>

          <p style={{ fontSize: 14, color: 'var(--muted)', marginBottom: 40 }}>
            Last updated: June 5, 2026
          </p>

          <div className="about-card" style={{
            background: 'var(--charcoal-2)',
            border: '1px solid rgba(255,255,255,0.07)',
            borderRadius: 32, padding: 32, marginBottom: 24,
          }}>
            <Section title="Acceptance">
              <p>By using ArgueBoss, you agree to these Terms of Service. If you do not agree, do not use the service.</p>
            </Section>

            <Section title="Description of Service">
              <p>ArgueBoss is an AI-powered fact-checking tool. You submit an argument, and the service analyzes it using large language models and web search to produce a verdict. The verdict is generated by AI and may contain errors or inaccuracies.</p>
            </Section>

            <Section title="User Responsibilities">
              <ul>
                <li>You must be at least 13 years old to use this service.</li>
                <li>You agree not to submit harmful, illegal, or abusive content.</li>
                <li>You are responsible for the accuracy of the arguments you submit.</li>
                <li>You must not attempt to bypass rate limits or abuse the service.</li>
              </ul>
            </Section>

            <Section title="No Professional Advice">
              <p>ArgueBoss verdicts are generated for entertainment and informational purposes only. They do not constitute professional, legal, medical, or financial advice. Always consult a qualified professional for important decisions.</p>
            </Section>

            <Section title="Account Security">
              <p>You are responsible for maintaining the confidentiality of your account credentials. Notify us immediately if you suspect unauthorized access.</p>
            </Section>

            <Section title="Intellectual Property">
              <p>The ArgueBoss name, logo, and branding are our property. The verdicts generated are provided to you for personal use. You may share verdict cards publicly, but you may not reproduce the service itself.</p>
            </Section>

            <Section title="Limitation of Liability">
              <p>ArgueBoss is provided &quot;as is&quot; without warranties of any kind. We are not liable for damages arising from your use of the service, including reliance on AI-generated verdicts.</p>
            </Section>

            <Section title="Termination">
              <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time via the <Link href="/delete-data" style={{ color: 'var(--red-light)' }}>Data Deletion page</Link>.</p>
            </Section>

            <Section title="Changes to Terms">
              <p>We may update these terms at any time. Continued use after changes constitutes acceptance of the new terms.</p>
            </Section>

            <Section title="Contact">
              <p>For questions about these terms, email <a href="mailto:legal@arguebot.app" style={{ color: 'var(--red-light)' }}>legal@arguebot.app</a>.</p>
            </Section>
          </div>

          <div style={{ textAlign: 'center', marginTop: 32 }}>
            <Link href="/" style={{
              display: 'inline-flex', alignItems: 'center', gap: 10,
              background: 'var(--red)', color: 'white',
              textDecoration: 'none', borderRadius: 20,
              padding: '16px 36px',
              fontFamily: "'Bebas Neue', sans-serif",
              fontSize: 22, letterSpacing: 2,
              boxShadow: '0 6px 24px var(--red-glow)',
              transition: 'all 0.2s',
            }}>
              BACK TO ARGUEBOSS
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2 style={{
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 22, letterSpacing: 1.5,
        color: 'var(--white)', marginBottom: 10,
      }}>{title}</h2>
      <div style={{ fontSize: 14, color: 'var(--muted)', lineHeight: 1.7 }}>
        {children}
      </div>
      <style>{`
        ul { padding-left: 20px; margin: 8px 0; }
        li { margin-bottom: 6px; }
      `}</style>
    </div>
  )
}
